Pintres/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include
from core.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('',include('comment.urls')),
    path('dashboard/',include('dashboard.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

comment/urls.py
from django.urls import path
from . import views
app_name='comment'
urlpatterns = [
    path('inbox/',views.inbox,name="inbox"),
    path('details/<int:pk>',views.details,name="details"),
    path('comment/<int:pk>',views.comment,name="comment"),
]

core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .forms import LoginForm
from . import views
app_name='core'
urlpatterns = [
    path('',views.index,name='index'),
    path('brows/',views.brows,name='brows'),
    path('login/',views.login,name='login'),
    path('about/',views.about,name='about'),
    path('contact/',views.contact,name='contact'),
    path('inbox/',views.contact_inbox,name='contact_inbox'),
    path('logout/',views.logout,name='logout'),
    path('singnup/',views.singnup,name='singnup'),
    path('details/<int:pk>',views.details,name='details'),
]

dashboard/urls.py
from django.urls import path
from . import views
app_name='dashboard'
urlpatterns = [
    path('dashboard/',views.dashboard,name='dashboard'),
    path('new/',views.new,name='new'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('profile/',views.profile,name='profile'),

    path('profile_user/',views.profile_user,name='profile_user'),
    path('edit_profile/',views.edit_profile,name='edit_profile'),
]

core/models.py
from django.db import models
class Contact(models.Model):
    name=models.CharField(max_length=100)
    Email=models.CharField(max_length=100)
    description=models.CharField(max_length=2000)
    def __str__(self):
        return self.name

# Create your models here.

core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import Contact


INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'
class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
    
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email address',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ('name', 'Email', 'description')
        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'Email': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
        }

core/views.py
from django.shortcuts import render,get_object_or_404,redirect,HttpResponse
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .forms import LoginForm,SignupForm,ContactForm
from item.models import Item,Category
from django.db.models import Q
from . models import Contact
def index(request):
    item_image=Item.objects.all()
    return render(request,'core/index.html',{'image':item_image})
def details(request,pk):
    items=get_object_or_404(Item,pk=pk)
    return render(request,'core/details.html',{'item':items})
def login(request):
    if request.method == 'POST':
        username = request.POST['Username']
        password = request.POST['Password']
        user = auth.authenticate(request, username=username, password=password)
        if user is not None:
            auth.login(request, user)
            return redirect('core:index')
        else:
            error_message = 'Invalid username or password'
            return render(request, 'core/login.html', {'error_message': error_message})
    else:
        return render(request, 'core/login.html')


def singnup(request):
    # if request.method == 'POST':
    #     form = SignupForm(request.POST)

    #     if form.is_valid():
    #         form.save()

    #         return redirect('/login/')
    # else:
    #     form = SignupForm()

    # form=SignupForm()
    if request.method == 'POST':
        username = request.POST['Username']
        email = request.POST['email']
        password1 = request.POST['Password1']
        password2 = request.POST['Password2']

        if password1 == password2:
            try:
                user = User.objects.create_user(username, email, password1)
                user.save()
                auth.login(request, user)
                return redirect('core:login')
            except:
                error_message = 'Error creating account'
                return render(request, 'core/singnup.html', {'error_message': error_message})
        else:
            error_message = 'Password dont match'
            return render(request, 'core/singnup.html', {'error_message': error_message})
    return render(request, 'core/singnup.html')

def logout(request):
    auth.logout(request)
    return redirect('core:index')
def brows(request):
    query = request.GET.get('search-data', '')
    category_id = request.GET.get('category', 0)
    category=Category.objects.all()
    item=Item.objects.all()
    if category_id:
        item = item.filter(category_id=category_id)

    if query:
        item = item.filter(Q(name__icontains=query) | Q(description__icontains=query))

    return render(request,"core/brows.html",{'category':category,'item':item,'query':query})

def contact(request):
    form=ContactForm()
    if request.method=='POST':
        form=ContactForm(request.POST)
        form.save()
        return redirect('core:contact')
    return render(request,'core/contact.html',{'form':form})

def contact_inbox(request):
    if request.user.is_superuser:
        contact=Contact.objects.all()
        print(contact)
        return render(request,'core/inbox.html',{'contact':contact})
    else:
        return HttpResponse('<h1>''I am sorry....''</h1>')
    
def about(request):
    return render(request,'core/about.html')
# Create your views here.

core/templates/core/about.html
{% extends "core/base.html" %}
{% block title %}details{% endblock  %}
{% block content %}
<section class="section-center">
    <!-- image -->
    <article class="gift-img">
      <img src="/media/item_images/aboutpic.jpg" alt="gift" />
    </article>
    <!-- info -->
    <article class="gift-info">
      <h3>Arvind kumar</h3>
      <h4 class="giveaway">
        this picture is created by
      </h4>
      <p>
        A Goldpic website is a online picture/image/photo sharing platform. this website you can download an image & upload an image on goldpic website and comment on any photo show that it is the best website for photo sharing on internet.and another task this website you are write a blog of any picture and you can write a new on this website...<b>Thanks</b>
      </p>
    </article>
  </section>
  
{% endblock  %}

core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Goldpic</title>

    <link rel="icon" href="https://img.freepik.com/free-vector/gradient-p-logo-template_23-2149372725.jpg?size=338&ext=jpg&ga=GA1.1.1700460183.1712793600&semt=ais" type="image/x-icon">
    <!-- font-awesome -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"
    />

    <!-- styles -->
    <link rel="stylesheet" href="/static/css/style.css?{% now "U" %}"/>
    <link rel="stylesheet" href="/static/css/details.css?{% now "U" %}"/>
    <link rel="stylesheet" href="/static/css/login_signup.css?{% now "U" %}"/>
    <link rel="stylesheet" href="/static/css/brows.css?{% now "U" %}"/>
    <link rel="stylesheet" href="/static/css/profile.css?{% now "U" %}"/>
    <link rel="stylesheet" href="/static/css/inbox.css?{% now "U" %}"/>
    <link rel="stylesheet" href="/static/css/upload.css?{% now "U" %}"/>
  </head>
  <body>
    <nav id="nav">
        <div class="nav-center">
            <div class="nav-header">
                <img src="https://img.freepik.com/free-vector/gradient-p-logo-template_23-2149372725.jpg?size=338&ext=jpg&ga=GA1.1.1700460183.1712793600&semt=ais" alt="no image" style="width:50px; height:50px; border-radius:50%;">
                {% comment %} <h2>Goldpic</h2> {% endcomment %}
                <button class="btn">
                    <i class="fas fa-bars"></i>
                </button>
            </div>
            <ul class="links">
                <li>
                    <a href="{% url "core:index" %}">Home</a>
                </li>
                <li>
                    {% if request.user.is_authenticated %}
                    <a href="{% url "dashboard:dashboard" %}">dashboard</a>
                    {% else %}
                    <a href="{% url "core:contact" %}">contact</a>
                    {% endif %}
                </li>
                <li>
                    <a href="{% url "core:brows" %}">Brows</a>
                </li>
                <li>
                    {% if request.user.is_authenticated %}
                    <a href="{% url "dashboard:new" %}">New vlog</a>
                    {% else %}
                    <a href="{% url "core:about" %}">About</a>
                    {% endif %}
                </li>
                <li>
                    {% if request.user.is_superuser %}
                    <a href="{% url "core:contact_inbox" %}">Contact Inbox</a>
                    {% endif %}
                </li>
            </ul>
            <!--social link-->
            <ul class="social-icon">
                <li>
                    {% if request.user.is_authenticated %}
                    <a href="{% url "core:logout" %}">
                    Logout
                    </a>
                    {% endif %}
                </li>
                <li>
                    {% if request.user.is_authenticated %}
                    <a href="{% url "comment:inbox" %}">
                       inbox
                    </a>
                    {% else %}
                    <a href="{% url "core:singnup" %}">
                        Sign
                     </a>
                    {% endif %}
                </li>
                <li>
                    {% if request.user.is_authenticated %}
                    <a href="{% url "dashboard:profile_user" %}">
                       {{request.user}}
                    </a>
                    {% else %}
                    <a href="{% url "core:login" %}">
                        Login
                     </a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </nav>
{% block content %}

{% endblock  %}

    <div class="foother">
        <p>
            copyright &copy; backroads travel tours company
            <span id="date"></span>. all rights reserved
          </p>
    </div>
    <!-- javascript -->
    <script src="/static/js/app.js"></script>
    <script src="/static/js/script.js"></script>
  </body>
</html>

core/templates/core/brows.html
{% extends "core/base.html" %}
{% block title %}Search{% endblock  %}
{% block content %}
<div class="brows-head">
    <div class="btn-container">
      {% for category in category %}
        <a href="{% url 'core:brows' %}?query={{ query }}&category={{ category.id }}"><button name="category-data" class="btn-category">{{category.name}}</button></a>
      {% endfor %}
    </div>
    <div class="search-box">
        <form method='get' action="{% url 'core:brows' %}">
        <input type="text" name="search-data" value={{query}}>
        <button class="btn-category" type='submit'>
            search
        </button>
    </form>
    </div>
</div>
<div class="servicehave">
    <h3 style="text-align: center;"><span>search</span>  item</h3>
      <div class="servicecontainer">
        {% for item in item %}
          <a href="{% url "core:details" item.id %}">
            <div>
              <img src="{{item.image.url}}" alt="" style="object-fit:cover;">
              
            </div>
          </a>
          {% endfor %}
      </div>
  </div>

{% endblock  %}

core/templates/core/contact.html
{% extends 'core/base.html' %}
{% block title %}contact{% endblock  %}

{% block content %}
<div class="container_new">
    <div class="new-box">
<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}

    <div>
        {{ form.as_p }}
    </div>
    {% if form.errors or form.non_field_errors %}
        <div>
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
    {% endif %}
    <button class="btn-category" type="Submit">Send</button>
</form>
</div>
</div>
{% endblock %}

core/templates/core/details.html
{% extends "core/base.html" %}
{% block title %}details{% endblock  %}
{% block content %}
<section class="section-center">
    <!-- image -->
    <article class="gift-img">
      <img src="{{item.image.url}}" alt="gift" />
    </article>
    <!-- info -->
    <article class="gift-info">
      <h3>{{item.name}}</h3>
      <h4 class="giveaway">
        this picture is created by..{{item.created_by}}
      </h4>
      <p>
        {{item.description}}
      </p>
    <a href="{{item.image.url}}" download>
      <button type="button" class="btn-comment">
            download
      </button>
    </a>
    <a href="{% url "comment:comment" item.id %}">
    <button type="button" class="btn-comment">
      comment
    </button>
    </a>
    {% if request.user == item.created_by %}
    <a href="{% url "dashboard:edit" item.id %}">
      <button type="button" class="btn-comment">
        edit
      </button>
      </a>
    {% endif %}
    </article>
  </section>
  
{% endblock  %}

core/templates/core/inbox.html
{% extends "core/base.html" %}
{% block content %}
    <h3 style="text-align: center;"><span>All</span>  comment</h3>
    <div class="inbox-container">
      <div class="inbox-box">
        {% for contact in contact %}
            <div class="inbox-contact">
                <h4>Name:{{contact.name}}</h4>
                <h4>Email:{{contact.Email}}</h4>
                <p>Massage:{{contact.description}}</p>
            </div>
          {% endfor %}
      </div>
  </div>

{% endblock  %}

core/templates/core/index.html
{% extends "core/base.html" %}
{% block title %}Home{% endblock  %}
{% block content %}
<div class="servicehave">
    <h3 style="text-align: center;"><span>Beautyfull</span>  Picture</h3>
      <div class="servicecontainer">
        {% for item in image %}
          <a href="{% url "core:details" item.id %}">
            <div>
              <img src="{{item.image.url}}" alt="" style="object-fit:cover;">
              
            </div>
          </a>
        {% endfor %}
      </div>
  </div>
{% endblock  %}

core/templates/core/login.html
{% extends "core/base.html" %}
{% block title %}login{% endblock  %}
{% block content %} 
<div class="container_login">
    <div class="login-page">
        <h3 style="padding: 5px;"><span style="color: cadetblue;">Log</span> in</h3>
        <form method="post">
            {% csrf_token %}
            <br>
            <input type="text" placeholder="Username" name="Username">
            <br>
            <input type="Password" placeholder="Password" name="Password">
            <br>
            <button class="btn-category" type="submit">Login</button>
        </form>
    </div>
</div>

{% endblock  %}

core/templates/core/singnup.html
{% extends "core/base.html" %}
{% block title %}Signup{% endblock  %}
{% block content %}
<div class="container_singnup">
    <div class="singnup-page">
        <h3 style="padding: 5px;"><span style="color: cadetblue;">singn</span> up</h3>
        <form method="post">
            {% csrf_token %}
            <br>
            <input type="text" placeholder="Username" name="Username">
            <br>
            <input type="text" placeholder="email" name="email">
            <br>
            <input type="Password" placeholder="Password1" name="Password1">
            <br>
            <input type="Password" placeholder="Password2" name="Password2">
            <br>
            <button class="btn-category" type='submit'>Singnup</button>
        </form>
    </div>
</div>
{% endblock  %}