Pintres/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path,include
from core.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('',include('comment.urls')),
    path('dashboard/',include('dashboard.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .forms import LoginForm
from . import views
app_name='core'
urlpatterns = [
    path('',views.index,name='index'),
    path('brows/',views.brows,name='brows'),
    path('login/',views.login,name='login'),
    path('about/',views.about,name='about'),
    path('contact/',views.contact,name='contact'),
    path('inbox/',views.contact_inbox,name='contact_inbox'),
    path('logout/',views.logout,name='logout'),
    path('singnup/',views.singnup,name='singnup'),
    path('details/<int:pk>',views.details,name='details'),
]

dashboard/urls.py
from django.urls import path
from . import views
app_name='dashboard'
urlpatterns = [
    path('dashboard/',views.dashboard,name='dashboard'),
    path('new/',views.new,name='new'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('profile/',views.profile,name='profile'),

    path('profile_user/',views.profile_user,name='profile_user'),
    path('edit_profile/',views.edit_profile,name='edit_profile'),
]

dashboard/models.py
from django.db import models
from item.models import Item
from django.contrib.auth.models import User

class Profile_user(models.Model):
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    name = models.CharField(max_length=255)
    email=models.CharField(max_length=100)
    number=models.CharField(max_length=1500)
    github=models.CharField(max_length=250)
    created_by=models.ForeignKey(User,on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name


class Profile(models.Model):
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    name = models.CharField(max_length=255)
    email=models.CharField(max_length=100)
    number=models.CharField(max_length=1500)
    github=models.CharField(max_length=250)
    twitter=models.CharField(max_length=250)
    file=models.FileField(upload_to='profile',blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.name

# Create your models here.

dashboard/forms.py
from django import forms

from .models import Profile,Profile_user
from item.models import Item

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'

class editprofileForm(forms.ModelForm):
    class Meta:
        model = Profile_user
        fields = ( 'name','email','number', 'github',  'image',)
        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'email': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'number': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'github': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            })
        }
class NewItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name', 'description', 'image',)
        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            })
        }

class EditItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('category', 'name', 'description', 'image',)
        widgets = {
            'category': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'price': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            })
        }

dashboard/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from item.models import Item,Category
from .forms import NewItemForm,editprofileForm,EditItemForm
from .models import Profile,Profile_user
from django.contrib.auth.models import User
import os


@login_required
def dashboard(request):
    items=Item.objects.filter(created_by=request.user)
    return render(request,'dashboard/dashboard.html',{'item':items})
@login_required
def new(request):
    if request.method == 'POST':
        form = NewItemForm(request.POST, request.FILES)

        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()

            return redirect('core:details',pk=item.id)
    else:
        form = NewItemForm()

    return render(request, 'dashboard/upload.html', {
        'form': form,
    })
def edit(request, pk):
    item = get_object_or_404(Item, pk=pk, created_by=request.user)

    if request.method == 'POST':
        form = EditItemForm(request.POST, request.FILES, instance=item)

        if form.is_valid():
            form.save()

            return redirect('core:details', pk=item.id)
    else:
        form = EditItemForm(instance=item)

    return render(request, 'dashboard/editupload.html', {
        'form': form,
        'title': 'Edit item',
    })

def profile_user(request):
    profile=Profile_user.objects.filter(created_by=request.user)
    if len(profile)==0:
        return redirect('dashboard:profile')
    return render(request,"dashboard/profile_user.html",{'profile':profile})
@login_required
def profile(request):
    if request.method == 'POST':
        form = editprofileForm(request.POST, request.FILES)

        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            item.save()
            return redirect('dashboard:profile_user')
    else:
        form = editprofileForm()

    form=editprofileForm()
    return render(request,'dashboard/profile.html',{'form':form})
def edit_profile(request):
    profile_data=Profile_user.objects.filter(created_by=request.user)
    data=''
    for i in profile_data:
        data=i
    if request.method == 'POST':
        form = editprofileForm(request.POST, request.FILES, instance=data)

        if form.is_valid():
            form.save()

            return redirect('dashboard:profile_user')
    else:
        form = editprofileForm(instance=data)

    return render(request,'dashboard/edit_profile.html',{'profile':data,'form':form})

# Create your views here.

dashboard/templates/dashboard/dashboard.html
{% extends "core/base.html" %}
{% block title %}dashboard{% endblock  %}
{% block content %}
<div class="servicehave">
    <h3 style="text-align: center;"><span>User uploaded</span>  Picture</h3>
      <div class="servicecontainer">
        {% for item in item %}
          <a href="{% url "core:details" item.id %}">
            <div>
              <img src="{{item.image.url}}" alt="noimage" style="object-fit:cover;">
              
            </div>
          </a>
        {% endfor %}
      </div>
  </div>
{% endblock  %}

dashboard/templates/dashboard/edit_profile.html
{% extends "core/base.html" %}
{% block content %}
<div class="profile-container">
  <div class="profile-box">
      <div class="profile">
        <form method="post" action="." enctype="multipart/form-data">
          {% csrf_token %}
          <img src="{{profile.image.url}}" alt="">
          <div>
              {{ form.as_p }}
          </div>
          {% if form.errors or form.non_field_errors %}
              <div>
                  {% for field in form %}
                      {{ field.errors }}
                  {% endfor %}
      
                  {{ form.non_field_errors }}
              </div>
          {% endif %}
          <button type="Submit" class="btn-category">Submit</button>
      </form>
      
      </div>
      <div class="user-item">
          <h2>About user</h2>
          <label for="">About-summary</label>
          <br>
          <textarea></textarea>
      </div>
  </div>
</div>


{% endblock  %}

dashboard/templates/dashboard/editupload.html
{% extends 'core/base.html' %}
{% block title %}new{% endblock  %}

{% block content %}
<div class="container_new">
    <div class="new-box">
<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}

    <div>
        {{ form.as_p }}
    </div>
    {% if form.errors or form.non_field_errors %}
        <div>
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
    {% endif %}
    <button class="btn-category" type="Submit">Submit</button>
</form>
</div>
</div>
{% endblock %}

dashboard/templates/dashboard/profile.html
{% extends "core/base.html" %}
{% block content %}
<div class="profile-container">
  <div class="profile-box">
      <div class="profile">
        <form method="post" action="." enctype="multipart/form-data">
          {% csrf_token %}
          <img src="#" alt="">
          <div>
              {{ form.as_p }}
          </div>
          {% if form.errors or form.non_field_errors %}
              <div>
                  {% for field in form %}
                      {{ field.errors }}
                  {% endfor %}
      
                  {{ form.non_field_errors }}
              </div>
          {% endif %}
          <button type="Submit" class="btn-category">Submit</button>
      </form>
      
      </div>
      <div class="user-item">
          <h2>About user</h2>
          <label for="">About-summary</label>
          <br>
          <textarea></textarea>
      </div>
  </div>
</div>


{% endblock  %}

dashboard/templates/dashboard/profile_user.html
{% extends "core/base.html" %}
{% block content %}
<div class="profile-container">
    <div class="profile-box">
        <div class="profile">
            <form action="">
            {% for profile in profile %}
            <img src="{{profile.image.url}}" alt="">
            <br>
            <input type="text" value='{{profile.name}}' name="name">
            <br>
            <input type="text" value='{{profile.email}}' name="email">
            <br>
            <input type="text" value='{{profile.number}}' name="phone">
            <br>
            <input type="text" value='{{profile.github}}' name="github-link">
            {% endfor %}
            <br>
            <button type="submit" class="btn-category">
                <a href="{% url "dashboard:edit_profile" %}">
                Edit
                </a>
            </button>
            </form>
        </div>
        <div class="user-item">
            <h2>About user</h2>
            <label for="">About-summary</label>
            <br>
            <textarea></textarea>
        </div>
    </div>
</div>

{% endblock  %}

dashboard/templates/dashboard/upload.html
{% extends 'core/base.html' %}
{% block title %}new{% endblock  %}

{% block content %}
<div class="container_new">
    <div class="new-box">
<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}

    <div>
        {{ form.as_p }}
    </div>
    {% if form.errors or form.non_field_errors %}
        <div>
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
    {% endif %}
    <button class="btn-category" type="Submit">Submit</button>
</form>
</div>
</div>
{% endblock %}